spring:
  application:
    name: spring-ai-rag

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rag-api?useSSL=false
    username: root
    password: 1234

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 1234

  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
    openai:
      api-key: ${OPEN-Ai-API-KEY}
      embedding:
        options:
          model: text-embedding-ada-002
      chat:
        options:
          model: zzz

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

key:
  open-ai: ${OPEN-Ai-API-KEY}